kind: Service
apiVersion: v1
metadata:
# this service shows up in the UI with this name
  name: interfaceengine
# namespace should match other services in this file  
  namespace: fabricrealtime  
# labels allows you to use selectors to find this service
  labels:
    app: interfaceengine
spec:
  ports:
# port that other services can use to connect to this service
  - port: 80
# port in the pod we map to  
    targetPort: 80
    protocol: TCP
    name: "http"
  - port: 8443
# port in the pod we map to  
    targetPort: 8443
    protocol: TCP
    name: "https"
  - port: 6661
# port in the pod we map to  
    targetPort: 6661
    protocol: TCP
    name: "channel"
# selector says this service should use a pod that has the "app: mysqlserver" label
  selector:
    app: interfaceengine
