kind: Service
apiVersion: v1
metadata:
# this service shows up in the UI with this name
  name: rabbitmq
# namespace should match other services in this file  
  namespace: fabricrealtime  
# labels allows you to use selectors to find this service
  labels:
    app: rabbitmq
spec:
  ports:
# port that other services can use to connect to this service
  - port: 5671
# port in the pod we map to  
    targetPort: 5671
    protocol: TCP
    name: "main"
  - port: 5672
  # port in the pod we map to  
    targetPort: 5672
    protocol: TCP
    name: "main2"   
  - port: 15672
# port in the pod we map to  
    targetPort: 15672
    protocol: TCP
    name: "mgmt"
# selector says this service should use a pod that has the "app: mysqlserver" label
  selector:
    app: rabbitmq
