apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-volume-certificateserver
  namespace: fabricrealtime
  labels:
    type: local  
spec:
  #persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/fabricrealtime"
  claimRef:
    namespace: fabricrealtime
    name: az-files-certificateserver
