apiVersion: v1
kind: PersistentVolume
metadata:
  name: realtime.rabbitmq
  namespace: fabricrealtime
  labels:
    type: azure
    namespace: fabricrealtime    
spec:
  storageClassName: default
  capacity:
    storage: 8Gi
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteMany
  # https://kubernetes.io/docs/api-reference/v1.8/#azurefilepersistentvolumesource-v1-core
  mountOptions:
  # we need to set owner of this to mysql user (999) so it has permissions to this folder
  # https://github.com/airdock-io/docker-base/wiki/Common-User-List
  # This should be 4204 according to documentation but is actually 999 in reality
    - uid=999
    - gid=999
  # and set permissions for the user to this folder
  # 0 no permissions
  # 1 execute
  # 2 write
  # 3 write & execute
  # 4 read
  # 5 read & execute
  # 6 read & write
  # 7 read write & execute  
  # in 0731 0 is ignore, the 7 applies to owner, 3 applies to group, 1 applies to everyone else
    - dir_mode=0731
    - file_mode=0764
  azureFile:
    secretName: azure-secret
    secretNamespace: default
    shareName: fabricrealtime
    readOnly: false
  claimRef:
    namespace: fabricrealtime
    name: realtime.rabbitmq
