apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: traefik-ui.minikube
    http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: solrserverpublic
  namespace: fabricnlp
spec:
  selector:
    app: solrserver
  ports:
  - port: 80
    targetPort: 8085
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: fabricnlp
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: solr.allina.healthcatalyst.net
    http:
      paths:
      - backend:
          serviceName: solrserverpublic
          servicePort: 80
