# Fabric NLP stack
#
# ---- Services internal to the cluster ----
# Solr service
kind: Service
apiVersion: v1
metadata:
# name of this service.  other
  name: solrserver
  namespace: fabricnlp  
  labels:
    app: solrserver
spec:
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
  selector:
    app: solrserver
---
# NLP service
kind: Service
apiVersion: v1
metadata:
# name of this service.  other
  name: nlpwebserver
  namespace: fabricnlp  
  labels:
    app: nlpwebserver
spec:
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: nlpwebserver
---
# NLP Jobs service
kind: Service
apiVersion: v1
metadata:
# name of this service.  other
  name: jobserver
  namespace: fabricnlp  
  labels:
    app: jobserver
spec:
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  selector:
    app: jobserver
---
# MySql service  
kind: Service
apiVersion: v1
metadata:
# this service shows up in the UI with this name
  name: mysqlserver
# namespace should match other services in this file  
  namespace: fabricnlp  
# labels allows you to use selectors to find this service
  labels:
    app: mysqlserver
spec:
  ports:
# port that other services can use to connect to this service
  - port: 3306
# port in the pod we map to  
    targetPort: 3306
    protocol: TCP
# selector says this service should use a pod that has the "app: mysqlserver" label
  selector:
    app: mysqlserver
---
# SMTP service for sending emails
kind: Service
apiVersion: v1
metadata:
  name: smtpserver
  namespace: fabricnlp  
  labels:
    app: smtpserver
spec:
  ports:
  - port: 25
    targetPort: 25
    protocol: TCP
  selector:
    app: smtpserver
---
# ----- Pods -----
# MySql pod
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
# name for this pod
  name: fabric.nlp.mysqlserver
# namespace for this pod
  namespace: fabricnlp  
  labels:
    app: mysqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlserver
  template:
    metadata:
      labels:
        app: mysqlserver
    spec:
      containers:
        # name of this pod
        - name: mysqlserver
          # image to pull
          image: healthcatalyst/fabric.nlp.docker.mysql:latest
          # specify to always pull a new image
          #imagePullPolicy: Always
          # environment variables
          env:
            - name: MYSQL_ROOT_PASSWORD
              # set the value of this environment variable from a secret called mysqlrootpassword
              valueFrom:
                secretKeyRef:
                  name: mysqlrootpassword
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
            - name: MYSQL_DATABASE
              # set the value of this environment variable directly
              value: nlpmt
            - name: MYSQL_USER
              value: NLP_APP_USER
          ports:
            # expose port 3306
            - containerPort: 3306
              # name of the port
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              # point the /var/lib/mysql folder inside the container to the volume called mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: az-files-mysql            
---
# SMTP server pod
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.smtpserver
  namespace: fabricnlp  
  labels:
    app: smtpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtpserver
  template:
    metadata:
      labels:
        app: smtpserver
    spec:
      containers:
        - name: smtpserver
          image: healthcatalyst/fabric.smtp.agent:latest
          #imagePullPolicy: Always          
---
# Solr pod
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.solrserver
  namespace: fabricnlp    
  labels:
    app: solrserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solrserver
  template:
    metadata:
      labels:
        app: solrserver
    spec:
      containers:
        - name: solrserver
          image: healthcatalyst/fabric.nlp.docker.solr:latest
          #imagePullPolicy: Always          
          volumeMounts:
            - name: solr-persistent-storage
              mountPath: /var/lib/solr
          ports:
            - containerPort: 8085
              name: solr
      volumes:
      - name: solr-persistent-storage
        persistentVolumeClaim:
          claimName: az-files-solr            
            
---
# NLP Job server pod
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.jobserver
  namespace: fabricnlp    
  labels:
    app: jobserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobserver
  template:
    metadata:
      labels:
        app: jobserver
    spec:
      containers:
        - name: jobserver
          image: healthcatalyst/fabric.nlp.docker.jobs:latest
          imagePullPolicy: Always          
          env:
            - name: EXTERNAL_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: certhostname
                  key: value
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
          ports:
            - containerPort: 8084
              name: jobserver
---
# NLP web server pod
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.nlpwebserver
  namespace: fabricnlp    
  labels:
    app: nlpwebserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlpwebserver
  template:
    metadata:
      labels:
        app: nlpwebserver
    spec:
      containers:
        - name: nlpwebserver
          image: healthcatalyst/fabric.nlp.docker.web:latest
          imagePullPolicy: Always          
          env:
            - name: EXTERNAL_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: certhostname
                  key: value
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
          ports:
            - containerPort: 8083
              name: nlpwebserver
---
