# define persistent volumes
# ----- MySql ----------
# Persistent Volume
kind: PersistentVolume
apiVersion: v1
metadata:
  name: azure-file-volume-mysql
  namespace: fabricnlp    
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  mountOptions:
  # we need to set owner of this to mysql user (999) so it has permissions to this folder
    - uid=999
    - gid=999
  # and set permissions for the user to this folder
  # 0 no permissions
  # 1 execute
  # 2 write
  # 3 write & execute
  # 4 read
  # 5 read & execute
  # 6 read & write
  # 7 read write & execute  
  # in 0731 0 is ignore, the 7 applies to owner, 3 applies to group, 1 applies to everyone else
    - dir_mode=0731
    - file_mode=0764
  claimRef:
    namespace: fabricnlp
    name: az-files-mysql
---
# Persistent Volume Claim
# claims have to be defined here otherwise when we remove the pods the volume goes into Released mode
# and we can't bind to that volume again until we delete the volume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: az-files-mysql
  namespace: fabricnlp    
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---      
# ---- Solr ------
# volume for solr
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-volume-solr
  namespace: fabricnlp
  labels:
    type: local  
spec:
  #persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  mountOptions:
    - dir_mode=0731
    - file_mode=0724
    - uid=1000
    - gid=1000
  claimRef:
    namespace: fabricnlp
    name: az-files-solr
---
# Persistent Volume Claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: az-files-solr
  namespace: fabricnlp  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
---

# ----- NLP Jobs -------
# volume for nlp jobs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-volume-jobs
  namespace: fabricnlp    
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  mountOptions:
    - dir_mode=0731
    - file_mode=0724
    - uid=1000
    - gid=1000
  claimRef:
    namespace: fabricnlp
    name: az-files-jobs
---
# Persistent Volume Claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: az-files-jobs
  namespace: fabricnlp  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
---
# ----- MySql Backup ----------
# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-volume-mysql-backup
  namespace: fabricnlp    
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  mountOptions:
  # we need to set owner of this to mysql user (999) so it has permissions to this folder
    - uid=999
    - gid=999
  # and set permissions for the user to this folder
  # 0 no permissions
  # 1 execute
  # 2 write
  # 3 write & execute
  # 4 read
  # 5 read & execute
  # 6 read & write
  # 7 read write & execute  
  # in 0731 0 is ignore, the 7 applies to owner, 3 applies to group, 1 applies to everyone else
    - dir_mode=0731
    - file_mode=0764
  claimRef:
    namespace: fabricnlp
    name: az-files-mysql-backup
---
# Persistent Volume Claim
# claims have to be defined here otherwise when we remove the pods the volume goes into Released mode
# and we can't bind to that volume again until we delete the volume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: az-files-mysql-backup
  namespace: fabricnlp  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
---
