# ingress for solr web server
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nlp-ingress
  namespace: fabricnlp
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: solr.allina.healthcatalyst.net
    http:
      paths:
      - backend:
          serviceName: solrserverpublic
          servicePort: 80
  - host: nlp.allina.healthcatalyst.net
    http:
      paths:
      - backend:
          serviceName: nlpserverpublic
          servicePort: 80
  - host: nlpjobs.allina.healthcatalyst.net
    http:
      paths:
      - backend:
          serviceName: nlpjobsserverpublic
          servicePort: 80
          
---          
# ----- Services exposed to the outside world ------
# solr web server
kind: Service
apiVersion: v1
metadata:
  name: solrserverpublic
  namespace: fabricnlp
spec:
  selector:
    app: solrserver
  ports:
  - port: 80
    targetPort: 8085
---
# nlp web server
kind: Service
apiVersion: v1
metadata:
  name: nlpserverpublic
  namespace: fabricnlp
spec:
  selector:
    app: nlpwebserver
  ports:
  - port: 80
    targetPort: 8083
---
# nlp jobs web server
kind: Service
apiVersion: v1
metadata:
  name: nlpjobsserverpublic
  namespace: fabricnlp
spec:
  selector:
    app: jobserver
  ports:
  - port: 80
    targetPort: 8084
---
# define persistent volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-volume-mysql
  namespace: fabricnlp    
spec:
  capacity:
    storage: 128Gi
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: default
    shareName: fabricnlp
    readOnly: false
  mountOptions:
  # we need to set owner of this to mysql user (999) so it has permissions to this folder
    - uid=999
    - gid=999
  # and set permissions for the user to this folder
  # 0 no permissions
  # 1 execute
  # 2 write
  # 3 write & execute
  # 4 read
  # 5 read & execute
  # 6 read & write
  # 7 read write & execute  
  # in 0731 0 is ignore, the 7 applies to owner, 3 applies to group, 1 applies to everyone else
    - dir_mode=0731
    - file_mode=0764
  claimRef:
    namespace: fabricnlp
    name: az-files-mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-volume-solr
  namespace: fabricnlp    
spec:
  capacity:
    storage: 128Gi
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: default
    shareName: fabricnlp
    readOnly: false
  mountOptions:
    - dir_mode=0731
    - file_mode=0724
    - uid=1000
    - gid=1000
  claimRef:
    namespace: fabricnlp
    name: az-files-solr
---
