# nlp-stack.yml
# https://docs.docker.com/compose/compose-file/#entrypoint
version: '3.3'  
networks:  
  nlpnet:
    driver: overlay

secrets:
  MySQLPassword:
    external: true
  MySQLRootPassword:
    external: true

services:  

  graylog:
    image: graylog2/server:latest
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"

  mysqlserver:
    image: healthcatalyst/fabric.nlp.docker.mysql
    networks: 
      - nlpnet
    secrets:
      - MySQLPassword
      - MySQLRootPassword
    environment: 
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MySQLRootPassword
      MYSQL_DATABASE: nlpmt
      MYSQL_USER: NLP_APP_USER
      MYSQL_PASSWORD_FILE: /run/secrets/MySQLPassword
    volumes:
      - type: bind
        source: ${SHARED_DRIVE_MYSQL}
        target: /var/lib/mysql
    ports:
      - 3306:3306
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://graylog:12201"
        tag: "mysql-events"      


  solrserver:
    image: healthcatalyst/fabric.nlp.docker.solr
    networks: 
      - nlpnet
    volumes:
      - type: bind
        source: ${SHARED_DRIVE_SOLR}
        target: /var/lib/solr
    ports: 
       - 8085:8085
    
  jobserver:
    image: healthcatalyst/fabric.nlp.docker.jobs
    networks: 
      - nlpnet
    environment: 
      nlpwebserverexternal: ${nlpwebserverexternal}
      smtpserver: ${smtpserver}
    ports: 
      - 8084:8084

  nlpwebserver:
    image: healthcatalyst/fabric.nlp.docker.web
    networks: 
      - nlpnet
    environment: 
      jobserverexternal: ${jobserverexternal}
      smtpserver: ${smtpserver}
    ports: 
      - 8083:8083
