# nlp-stack.yml
# https://docs.docker.com/compose/compose-file/#entrypoint
version: '3.3'  
networks:  
  nlpnet:
    driver: overlay

secrets:
  MySQLPassword:
    external: true
  MySQLRootPassword:
    external: true
  ExternalHostName:
    external: true

services:  

  # https://docs.docker.com/engine/admin/logging/fluentd/
  fluentd:
    image: fluent/fluentd
    networks: 
      - nlpnet
    volumes:
      - type: bind
        source: ${SHARED_DRIVE_LOGS}
        target: /fluentd/log
    ports:
      - 24224:24224
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s      

  # logstash:
  #   image: healthcatalyst/fabric.docker.logger
  #   networks: 
  #     - nlpnet
  #   volumes:
  #     - type: bind
  #       source: c:/tmp/logstash
  #       target: /var/log/logstash/
  #   ports:
  #     - 12201:12201
  #   logging:
  #     driver: fluentd
  #     options:
  #       tag: logstash

  mysqlserver:
    image: healthcatalyst/fabric.nlp.docker.mysql
    networks: 
      - nlpnet
    secrets:
      - MySQLPassword
      - MySQLRootPassword
    environment: 
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MySQLRootPassword
      MYSQL_DATABASE: nlpmt
      MYSQL_USER: NLP_APP_USER
      MYSQL_PASSWORD_FILE: /run/secrets/MySQLPassword
    volumes:
      - type: bind
        source: ${SHARED_DRIVE_MYSQL}
        target: /var/lib/mysql
    ports:
      - 3306:3306
    logging:
      driver: fluentd
      options:
        tag: mysqlserver
        fluentd-async-connect: 1
    # logging:
    #   driver: fluentd
    #   options:
    #     tag: mysqlserver
    #     gelf-address: udp://127.0.0.1:12201

  solrserver:
    image: healthcatalyst/fabric.nlp.docker.solr
    networks: 
      - nlpnet
    volumes:
      - type: bind
        source: ${SHARED_DRIVE_SOLR}
        target: /var/lib/solr
    ports: 
       - 8085:8085
    logging:
      driver: fluentd
      options:
        tag: solrserver
        fluentd-async-connect: 1        
    
  jobserver:
    image: healthcatalyst/fabric.nlp.docker.jobs
    networks: 
      - nlpnet
    secrets:
      - ExternalHostName
    environment: 
      EXTERNAL_HOSTNAME_FILE: /run/secrets/ExternalHostName
      smtpserver: ""
    ports: 
      - 8084:8084
    logging:
      driver: fluentd
      options:
        tag: jobserver
        fluentd-async-connect: 1        

  nlpwebserver:
    image: healthcatalyst/fabric.nlp.docker.web
    networks: 
      - nlpnet
    secrets:
      - ExternalHostName
    environment: 
      EXTERNAL_HOSTNAME_FILE: /run/secrets/ExternalHostName
      smtpserver: ""
    logging:
      driver: fluentd
      options:
        tag: nlpwebserver
        fluentd-async-connect: 1        
    ports: 
      - 8083:8083
