kind: Service
apiVersion: v1
metadata:
  name: mysqlserver
  namespace: fabricnlp  
  labels:
    app: mysqlserver
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysqlserver
---
kind: Service
apiVersion: v1
metadata:
  name: solrserver
  namespace: fabricnlp  
  labels:
    app: solrserver
spec:
  type: LoadBalancer
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
  selector:
    app: solrserver
status: 
    loadBalancer: {}
---
kind: Service
apiVersion: v1
metadata:
  name: smtpserver
  namespace: fabricnlp  
  labels:
    app: smtpserver
spec:
  ports:
  - port: 25
    targetPort: 25
    protocol: TCP
  selector:
    app: smtpserver
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.mysqlserver
  namespace: fabricnlp  
  labels:
    app: mysqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlserver
  template:
    metadata:
      labels:
        app: mysqlserver
    spec:
      containers:
        - name: mysqlserver
          image: healthcatalyst/fabric.nlp.docker.mysql
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlrootpassword
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
            - name: MYSQL_DATABASE
              value: nlpmt
            - name: MYSQL_USER
              value: NLP_APP_USER
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /data/mysql
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.smtpserver
  namespace: fabricnlp  
  labels:
    app: smtpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtpserver
  template:
    metadata:
      labels:
        app: smtpserver
    spec:
      containers:
        - name: smtpserver
          image: healthcatalyst/fabric.smtp.agent
          imagePullPolicy: Always          
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.solrserver
  namespace: fabricnlp    
  labels:
    app: solrserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solrserver
  template:
    metadata:
      labels:
        app: solrserver
    spec:
      containers:
        - name: solrserver
          image: healthcatalyst/fabric.nlp.docker.solr
          imagePullPolicy: Always          
          volumeMounts:
            - name: solr-persistent-storage
              mountPath: /var/lib/solr
          ports:
            - containerPort: 8085
              name: solr

      volumes:
        - name: solr-persistent-storage
          hostPath:
            path: /data/solr
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.jobserver
  namespace: fabricnlp    
  labels:
    app: jobserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobserver
  template:
    metadata:
      labels:
        app: jobserver
    spec:
      containers:
        - name: jobserver
          image: healthcatalyst/fabric.nlp.docker.jobs
          imagePullPolicy: Always          
          env:
            - name: EXTERNAL_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: certhostname
                  key: value
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
          ports:
            - containerPort: 8084
              name: jobserver
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.nlpwebserver
  namespace: fabricnlp    
  labels:
    app: nlpwebserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlpwebserver
  template:
    metadata:
      labels:
        app: nlpwebserver
    spec:
      containers:
        - name: nlpwebserver
          image: healthcatalyst/fabric.nlp.docker.web
          imagePullPolicy: Always          
          env:
            - name: EXTERNAL_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: certhostname
                  key: value
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
          ports:
            - containerPort: 8083
              name: nlpwebserver
