apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"cafe.healthcatalyst.com": ["10.5.2.4","10.5.2.15"]}
  upstreamNameservers: |
    ["10.5.2.4","10.5.2.15"]