# from http://blog.kubernetes.io/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes.html
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"cafe.healthcatalyst.com": ["10.5.2.4","10.5.2.15"]}
  upstreamNameservers: |
    ["10.5.2.4","10.5.2.15","8.8.8.8", "8.8.4.4"]