# Traefik Ingress reverse proxy
# based on https://github.com/containous/traefik/issues/2329

# the config for Traefik so it knows where the certificates are
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
  labels:
    k8s-traefik: traefik  
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          # TLS certs for Allina (AHMN): *.ahmn.healthcatalyst.net
          CertFile = "/ssl/ahmn/tls.crt"
          KeyFile = "/ssl/ahmn/tls.key"
          # [[entryPoints.https.tls.certificates]]
          # CertFile = "/ssl/ahmn/tls.crt"
          # KeyFile = "/ssl/ahmn/tls.key"        
---
# service account to use for running the traefik ingress service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller-serviceaccount
  namespace: kube-system
---
# deployment of the pods for traefik service
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
    k8s-traefik: traefik  
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller-serviceaccount
      terminationGracePeriodSeconds: 60
      volumes:
        - name: ssl-ahmn
          secret:
            secretName: traefik-cert-ahmn
        # - name: ssl-ahmn
        #   secret:
        #     secretName: traefik-cert-ahmn
        - name: config
          configMap:
            name: traefik-conf
      containers:
      - image: traefik
        name: traefik-ingress-lb
        volumeMounts:
          - mountPath: "/config"
            name: "config"        
          - mountPath: "/ssl/ahmn"
            name: "ssl-ahmn" 
          # - mountPath: "/ssl/ahmn"
          #   name: "ssl-ahmn" 
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 8080
        args:
        - --web
        - --kubernetes
        - --configfile=/config/traefik.toml
        - --logLevel=DEBUG
---
# service definition for traefik
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: kube-system
  labels:
    k8s-traefik: traefik  
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - port: 80
    targetPort: 8080
---
# ingress for the Traefik admin ui
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
  labels:
    k8s-traefik: traefik  
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: dashboard.CUSTOMERID.healthcatalyst.net
    http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: 80
---
# default backend so if no rules match it goes here
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-default-route
  namespace: kube-system
  labels:
    k8s-traefik: traefik    
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: 80         
---
