# ----- Services exposed to the outside world ------
# solr web server
kind: Service
apiVersion: v1
metadata:
  name: interfaceenginepublic
  namespace: fabricrealtime
spec:
  selector:
    app: interfaceengine
  ports:
  - port: 80
    targetPort: 80
    name: "http"
  - port: 8443
    targetPort: 8443
    name: "https"
---
