# ----- Services exposed to the outside world ------
# solr web server
kind: Service
apiVersion: v1
metadata:
  name: rabbitmqpublic
  namespace: fabricrealtime
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 80
    targetPort: 15672
---
