# format: https://docs.traefik.io/configuration/backends/kubernetes/
# the config for Traefik so it knows where the certificates are
# https://docs.traefik.io/configuration/commons/
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
  labels:
    k8s-traefik: traefik  
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http"]
    [accessLog]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
    [kubernetes]
      namespaces = ["default","kube-system","fabricnlp"]

