# Traefik Ingress reverse proxy
# based on https://github.com/containous/traefik/issues/2329

# the config for Traefik so it knows where the certificates are
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
  labels:
    k8s-traefik: traefik  
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [accessLog]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]      
