# default backend so if no rules match it goes here
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-default-route
  namespace: kube-system
  labels:
    k8s-traefik: traefik  
    expose: external
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: traefik-dashboard
          servicePort: 80         