kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.jobserver
  namespace: fabricnlp    
  labels:
    app: jobserver
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate        
  selector:
    matchLabels:
      app: jobserver
  template:
    metadata:
      labels:
        app: jobserver
    spec:
      containers:
        - name: jobserver
          image: healthcatalyst/fabric.nlp.docker.jobs:1
          imagePullPolicy: Always          
          env:
            - name: NLPWEB_EXTERNAL_URL
              valueFrom:
                secretKeyRef:
                  name: nlpweb-external-url
                  key: url
            - name: JOBSERVER_EXTERNAL_URL
              valueFrom:
                secretKeyRef:
                  name: jobserver-external-url
                  key: url
            # - name: EXTERNAL_HOSTNAME
            #   value: localhost
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
          ports:
            - containerPort: 8084
              name: jobserver
          # livenessProbe:
          #   httpGet:
          #     path: /nlp
          #     port: 8084
          #   initialDelaySeconds: 60
          #   periodSeconds: 60
          volumeMounts:
            - name: jobs-persistent-storage
              mountPath: /opt/jobWork/
              subPath: jobs
      volumes:
      - name: jobs-persistent-storage
        persistentVolumeClaim:
          claimName: nlp.jobserver            
