kind: Deployment
apiVersion: extensions/v1beta1
metadata:
# name for this pod
  name: fabric.nlp.mysqlserver
# namespace for this pod
  namespace: fabricnlp  
  labels:
    app: mysqlserver
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate        
  selector:
    matchLabels:
      app: mysqlserver
  template:
    metadata:
      labels:
        app: mysqlserver
    spec:
      containers:
        # name of this pod
        - name: mysqlserver
          # image to pull
          image: healthcatalyst/fabric.nlp.docker.mysql:latest
          # specify to always pull a new image
          imagePullPolicy: Always
          # environment variables
          env:
            - name: MYSQL_ROOT_PASSWORD
              # set the value of this environment variable from a secret called mysqlrootpassword
              valueFrom:
                secretKeyRef:
                  name: mysqlrootpassword
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
            - name: MYSQL_DATABASE
              # set the value of this environment variable directly
              value: nlpmt
            - name: MYSQL_USER
              value: NLP_APP_USER
          ports:
            # expose port 3306
            - containerPort: 3306
              # name of the port
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              # point the /var/lib/mysql folder inside the container to the volume called mysql-persistent-storage
              mountPath: /var/lib/mysql
              subPath: mysql              
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: nlp.mysqlserver            
