kind: Deployment
apiVersion: extensions/v1beta1
metadata:
# name for this pod
  name: fabric.nlp.mysqlclient
# namespace for this pod
  namespace: fabricnlp  
  labels:
    app: mysqlclient
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate        
  selector:
    matchLabels:
      app: mysqlclient
  template:
    metadata:
      labels:
        app: mysqlclient
    spec:
      containers:
      - image: healthcatalyst/fabric.mysqlclient:latest
        # command:
        #   - sleep
        #   - "3600"
        # # this overrides the CMD command in docker
        args: ["sleep"]
        imagePullPolicy: Always
        name: mysqlclient
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlpassword
                key: password
          - name: MYSQL_DATABASE
            # set the value of this environment variable directly
            value: nlpmt
          - name: MYSQL_USER
            value: NLP_APP_USER
          - name: MYSQL_SERVER
            value: mysqlserver
          - name: BACKUP_NAME_PREFIX
            value: "nlpsql"
        volumeMounts:
          - name: mysql-persistent-storage-backup
            # point the /var/lib/mysql folder inside the container to the volume called mysql-persistent-storage
            mountPath: /var/lib/mysql
            subPath: mysqlbackups              
      volumes:
      - name: mysql-persistent-storage-backup
        persistentVolumeClaim:
          claimName: nlp.mysqlbackup
---
