kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fabric.nlp.solrserver
  namespace: fabricnlp    
  labels:
    app: solrserver
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate        
  selector:
    matchLabels:
      app: solrserver
  template:
    metadata:
      labels:
        app: solrserver
    spec:
      containers:
        - name: solrserver
          image: healthcatalyst/fabric.nlp.docker.solr:latest
          imagePullPolicy: Always          
          volumeMounts:
            - name: solr-persistent-storage
              mountPath: /var/lib/solr
              subPath: solr
          ports:
            - containerPort: 8085
              name: solr
          # livenessProbe:
          #   httpGet:
          #     path: /solr
          #     port: 8085
          #   initialDelaySeconds: 60
          #   periodSeconds: 60 
      # give pod more time to finish solr indexing
      terminationGracePeriodSeconds: 10      
      volumes:
      - name: solr-persistent-storage
        persistentVolumeClaim:
          claimName: nlp.solrserver            
