apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-volume-jobs
  namespace: fabricnlp    
spec:
  capacity:
    storage: 32Gi
  storageClassName: default
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: default
    shareName: fabricnlp
    readOnly: false
  mountOptions:
    - dir_mode=0731
    - file_mode=0724
    - uid=1000
    - gid=1000
  claimRef:
    namespace: fabricnlp
    name: az-files-jobs
