apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-volume-jobs
  namespace: fabricnlp
  labels:
    type: local  
spec:
  #persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: fabricnlp
    name: az-files-jobs
