apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-volume-mysql-backup
  namespace: fabricnlp    
  labels:
    type: local  
    namespace: fabricnlp  
spec:
  storageClassName: default
  capacity:
    storage: 16Gi
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: fabricnlp
    name: nlp.mysqlbackup
