apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-volume-mysql-backup
  namespace: fabricnlp    
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: fabricnlp
    name: az-files-mysql-backup
