kind: PersistentVolume
apiVersion: v1
metadata:
  name: azure-file-volume-mysql
  namespace: fabricnlp    
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: fabricnlp
    name: az-files-mysql
