apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-volume-solr
  namespace: fabricnlp
  labels:
    type: local  
spec:
  #persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: fabricnlp
    name: az-files-solr
