# ----- Services exposed to the outside world ------
# solr web server
kind: Service
apiVersion: v1
metadata:
  name: solrserverpublic
  namespace: fabricrealtime
spec:
  selector:
    app: solrserver
  ports:
  - port: 80
    targetPort: 8085
---
# nlp web server
kind: Service
apiVersion: v1
metadata:
  name: nlpserverpublic
  namespace: fabricrealtime
spec:
  selector:
    app: nlpwebserver
  ports:
  - port: 80
    targetPort: 8083
---
# nlp jobs web server
kind: Service
apiVersion: v1
metadata:
  name: nlpjobsserverpublic
  namespace: fabricrealtime
spec:
  selector:
    app: jobserver
  ports:
  - port: 80
    targetPort: 8084
---
