apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fabric.realtime
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysqlserver
          image: healthcatalyst/fabric.realtime.mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlrootpassword
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
            - name: MYSQL_DATABASE
              value: mirthdb
            - name: MYSQL_USER
              value: mirthuser
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
        - name: certificateserver
          image: healthcatalyst/fabric.certificateserver
          env:
            - name: CERT_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: certhostname
                  key: value
            - name: CERT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: certpassword
                  key: password
            - name: CLIENT_CERT_USERNAME
              value: fabricrabbitmquser
          ports:
          - containerPort: 3000
          resources: {}
          volumeMounts:
          - mountPath: /opt/certs/
            name: certificateserver-storage
              
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /data/mysql
        - name: certificateserver-storage
          hostPath:
            path: /data/mysql
