# realtime-stack.yml
# https://docs.docker.com/compose/compose-file/#entrypoint
version: '3.3'  
networks:  
  realtimenet:
    driver: overlay

secrets:
  RabbitMqMgmtUiPassword:
    external: true  
  CertPassword:
    external: true
  CertHostName:
    external: true
  SqlServerUserName:
    external: true
  SqlServerPassword:
    external: true
  SqlServerDomain:
    external: true
  SqlServerADUrl:
    external: true
  SqlServerName:
    external: true
  SqlServerDatabase:
    external: true


services:  

  certificateserver:
    image: healthcatalyst/fabric.certificateserver:1
    networks: 
      - realtimenet
    secrets:
      - CertPassword
      - CertHostName
    environment: 
      CERT_HOSTNAME_FILE: /run/secrets/CertHostName
      CERT_PASSWORD_FILE: /run/secrets/CertPassword
      CLIENT_CERT_USERNAME: fabricrabbitmquser
    volumes: 
      - ${SHARED_DRIVE_CERTS}:/opt/certs/     
    deploy:
      replicas: 1
    ports: 
       - 8081:3000    
    
  rabbitmq:
    image: healthcatalyst/fabric.realtime.rabbitmq:1
    networks: 
      - realtimenet
    secrets:
      - RabbitMqMgmtUiPassword
      - CertHostName
    environment: 
      CERT_HOSTNAME_FILE: /run/secrets/CertHostName
      RABBITMQ_MGMT_UI_PASSWORD_FILE: /run/secrets/RabbitMqMgmtUiPassword
      RABBITMQ_MNESIA_BASE: /opt/rabbitmq
      DISABLE_SSL: "${DISABLE_SSL}"
    volumes: 
      - type: bind
        source: ${SHARED_DRIVE_CERTS}
        target: /opt/healthcatalyst/
      - type: bind
        source: ${SHARED_DRIVE_RABBITMQ}
        target: /opt/rabbitmq
    deploy:
      replicas: 1
    ports: 
       - 5671:5671
       - 15672:15672

  interfaceengine:
    image: healthcatalyst/fabric.docker.interfaceengine:1
    networks: 
      - realtimenet
    secrets:
      - SqlServerUserName
      - SqlServerPassword
      - SqlServerDomain
      - SqlServerADUrl
      - SqlServerName
      - SqlServerDatabase
    environment: 
      SQLSERVER_USER_FILE: /run/secrets/SqlServerUserName
      SQLSERVER_PASSWORD_FILE: /run/secrets/SqlServerPassword
      SQLSERVER_DOMAIN_FILE: /run/secrets/SqlServerDomain
      SQLSERVER_AD_URL_FILE: /run/secrets/SqlServerADUrl
      SQLSERVER_SERVER_FILE: /run/secrets/SqlServerName
      SQLSERVER_DATABASE_FILE: /run/secrets/SqlServerDatabase
    ports:
      - 8080:8080
      - 8443:8443
      - 6661:6661


