# --- MySql ---
# Pod
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
# name for this pod
  name: mysqlserver
# namespace for this pod
  namespace: fabricrealtime  
  labels:
    app: mysqlserver
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate        
  selector:
    matchLabels:
      app: mysqlserver
  template:
    metadata:
      labels:
        app: mysqlserver
    spec:
      containers:
        # name of this pod
        - name: mysqlserver
          # image to pull
          image: healthcatalyst/fabric.realtime.mysql:latest
          # specify to always pull a new image
          imagePullPolicy: Always
          # environment variables
          env:
            - name: MYSQL_ROOT_PASSWORD
              # set the value of this environment variable from a secret called mysqlrootpassword
              valueFrom:
                secretKeyRef:
                  name: mysqlrootpassword
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
            - name: MYSQL_DATABASE
              # set the value of this environment variable directly
              value: mirthdb
            - name: MYSQL_USER
              value: mirthuser
          ports:
            # expose port 3306
            - containerPort: 3306
              # name of the port
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              # point the /var/lib/mysql folder inside the container to the volume called mysql-persistent-storage
              mountPath: /var/lib/mysql
              subPath: mysql              
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: az-files-mysql            
---
# Service
kind: Service
apiVersion: v1
metadata:
# this service shows up in the UI with this name
  name: mysqlserver
# namespace should match other services in this file  
  namespace: fabricrealtime  
# labels allows you to use selectors to find this service
  labels:
    app: mysqlserver
spec:
  ports:
# port that other services can use to connect to this service
  - port: 3306
# port in the pod we map to  
    targetPort: 3306
    protocol: TCP
# selector says this service should use a pod that has the "app: mysqlserver" label
  selector:
    app: mysqlserver
---
# -- end of MySql ---

# --- Certificate Server ---
# Pod
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
# name for this pod
  name: certificateserver
# namespace for this pod
  namespace: fabricrealtime  
  labels:
    app: certificateserver
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate        
  selector:
    matchLabels:
      app: certificateserver
  template:
    metadata:
      labels:
        app: certificateserver
    spec:
      containers:
        # name of this pod
        - name: certificateserver
          # image to pull
          image: healthcatalyst/fabric.certificateserver:latest
          # specify to always pull a new image
          imagePullPolicy: Always
          # environment variables
          env:
            - name: CERT_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: certhostname
                  key: value
            - name: CERT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: certpassword
                  key: password
            - name: CLIENT_CERT_USERNAME
              value: fabricrabbitmquser
          ports:
            # expose port 3000
            - containerPort: 3000
              # name of the port
              name: certserver
          volumeMounts:
            - name: certificateserver-persistent-storage
              # point the /var/lib/mysql folder inside the container to the volume called mysql-persistent-storage
              mountPath: /opt/certs/
              subPath: certs              
      volumes:
      - name: certificateserver-persistent-storage
        persistentVolumeClaim:
          claimName: az-files-certificateserver            
---
# Service
kind: Service
apiVersion: v1
metadata:
# this service shows up in the UI with this name
  name: certificateserver
# namespace should match other services in this file  
  namespace: fabricrealtime  
# labels allows you to use selectors to find this service
  labels:
    app: certificateserver
spec:
  ports:
# port that other services can use to connect to this service
  - port: 8801
# port in the pod we map to  
    targetPort: 3000
    protocol: TCP
# selector says this service should use a pod that has the "app: mysqlserver" label
  selector:
    app: certificateserver
---
# -- end of Certificateserver ---

# --- RabbitMq Server ---
# Pod
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
# name for this pod
  name: rabbitmq
# namespace for this pod
  namespace: fabricrealtime  
  labels:
    app: rabbitmq
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate        
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        # name of this pod
        - name: rabbitmq
          # image to pull
          image: healthcatalyst/fabric.realtime.rabbitmq:latest
          # specify to always pull a new image
          imagePullPolicy: Always
          # environment variables
          env:
            - name: CERT_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: certhostname
                  key: value
            - name: RABBITMQ_MGMT_UI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmqmgmtuipassword
                  key: password
            - name: RABBITMQ_MNESIA_BASE
              value: "/opt/rabbitmq"
            - name: RABBITMQ_LOGS
              value: "-"
          ports:
            # expose port 3000
            - containerPort: 5671
              # name of the port
              name: rabbitmq
            - containerPort: 15672
              # name of the port
              name: rabbitmqmgmt
          volumeMounts:
            - name: rabbitmqcert-persistent-storage
              # point the /var/lib/mysql folder inside the container to the volume called mysql-persistent-storage
              mountPath: /opt/healthcatalyst/
              subPath: certs              
            - name: rabbitmq-persistent-storage
              # point the /var/lib/mysql folder inside the container to the volume called mysql-persistent-storage
              mountPath: /opt/rabbitmq
              subPath: rabbitmq    
      volumes:
      - name: rabbitmqcert-persistent-storage
        persistentVolumeClaim:
          claimName: az-files-rabbitmqcert            
      - name: rabbitmq-persistent-storage
        persistentVolumeClaim:
          claimName: az-files-rabbitmq            
---
# Service
kind: Service
apiVersion: v1
metadata:
# this service shows up in the UI with this name
  name: rabbitmq
# namespace should match other services in this file  
  namespace: fabricrealtime  
# labels allows you to use selectors to find this service
  labels:
    app: rabbitmq
spec:
  ports:
# port that other services can use to connect to this service
  - port: 5671
# port in the pod we map to  
    targetPort: 5671
    protocol: TCP
    name: "main"
  - port: 15672
# port in the pod we map to  
    targetPort: 15672
    protocol: TCP
    name: "mgmt"
# selector says this service should use a pod that has the "app: mysqlserver" label
  selector:
    app: rabbitmq
---
# -- end of rabbitmq ---

# --- Interface Engine ---
# Pod
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
# name for this pod
  name: interfaceengine
# namespace for this pod
  namespace: fabricrealtime  
  labels:
    app: interfaceengine
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate        
  selector:
    matchLabels:
      app: interfaceengine
  template:
    metadata:
      labels:
        app: interfaceengine
    spec:
      containers:
        # name of this pod
        - name: interfaceengine
          # image to pull
          image: healthcatalyst/fabric.docker.interfaceengine:latest
          # specify to always pull a new image
          imagePullPolicy: Always
          # environment variables
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
            - name: MYSQL_DATABASE
              value: mirthdb
            - name: MYSQL_USER
              value: mirthuser
          ports:
            # expose port 3000
            - containerPort: 8080
              # name of the port
              name: http
            - containerPort: 8443
              # name of the port
              name: https 
            - containerPort: 6661
              # name of the port
              name: channel 
---
# Service
kind: Service
apiVersion: v1
metadata:
# this service shows up in the UI with this name
  name: interfaceengine
# namespace should match other services in this file  
  namespace: fabricrealtime  
# labels allows you to use selectors to find this service
  labels:
    app: interfaceengine
spec:
  ports:
# port that other services can use to connect to this service
  - port: 8080
# port in the pod we map to  
    targetPort: 8080
    protocol: TCP
    name: "http"
  - port: 8443
# port in the pod we map to  
    targetPort: 8443
    protocol: TCP
    name: "https"
  - port: 8443
# port in the pod we map to  
    targetPort: 6661
    protocol: TCP
    name: "https"
# selector says this service should use a pod that has the "app: mysqlserver" label
  selector:
    app: interfaceengine
---
# -- end of interfaceengine ---