kind: Service
apiVersion: v1
metadata:
# name of this service.  other
  name: solrserver
  namespace: fabricnlp  
  labels:
    app: solrserver
spec:
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
  selector:
    app: solrserver
---