# https://github.com/kubernetes/contrib/tree/master/for-demos/proxy-to-service
# https://stackoverflow.com/questions/47057176/how-to-access-kubernetes-service-externally-on-bare-metal-install
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
# name for this pod
  name: tcp-proxy-rabbitmq
# namespace for this pod
  namespace: fabricrealtime  
  labels:
    app: rabbitmq
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    type: Recreate        
  selector:
    matchLabels:
      app: tcp-proxy-rabbitmq
  template:
    metadata:
      labels:
        app: tcp-proxy-rabbitmq
    spec:
      # hostPort is broken on CNI (https://github.com/kubernetes/kubernetes/issues/31307) we have to use hostNetwork where CNI is used
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      # run on master node so we use the IP of the master
      # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
      # https://ekartco.com/2017/09/kubernetes-make-pods-run-on-your-master-nodes/
      nodeSelector:
        node-role.kubernetes.io/master: ""
      # https://stackoverflow.com/questions/41999756/how-to-force-pods-deployments-to-master-nodes
      # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: proxy-tcp
        image: healthcatalyst/tcp-proxy:latest
        imagePullPolicy: Always
        args: [ "tcp", "5671", "rabbitmq.fabricrealtime.svc.cluster.local" ]
        ports:
        - name: tcp
          protocol: TCP
          containerPort: 5671
---
