kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller-internal
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb-internal
    k8s-traefik: traefik  
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb-internal
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb-internal
        name: traefik-ingress-lb-internal
        k8s-traefik: traefik          
    spec:
      serviceAccountName: traefik-ingress-serviceaccount
      terminationGracePeriodSeconds: 60
      volumes:
        - name: ssl-ahmn
          secret:
            secretName: traefik-cert-ahmn
        # - name: ssl-ahmn
        #   secret:
        #     secretName: traefik-cert-ahmn
        - name: config
          configMap:
            name: traefik-conf
      containers:
      - image: traefik:1.5
        name: traefik-ingress-lb-internal
        imagePullPolicy: Always        
        volumeMounts:
          - mountPath: "/config"
            name: "config"        
          - mountPath: "/ssl/ahmn"
            name: "ssl-ahmn"             
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 8080
        args:
        - --web
        - --kubernetes
        - --configfile=/config/traefik.toml
        - --logLevel=DEBUG
        - --kubernetes.labelselector=expose=internal    
        # - --kubernetes.namespaces=["default","kube-system","fabricnlp"]
        - --kubernetes.debugloggeneratedtemplate
        - --kubernetes.trace
        - --debug            
        # https://github.com/kubernetes/ingress-nginx/blob/master/README.md#running-multiple-ingress-controllers
        # https://docs.traefik.io/user-guide/kubernetes/
---
