kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
    k8s-traefik: traefik  
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
        k8s-traefik: traefik          
    spec:
      serviceAccountName: traefik-ingress-serviceaccount
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-conf
      containers:
      - image: traefik:1.5.3
        name: traefik-ingress-lb
        imagePullPolicy: Always        
        volumeMounts:
          - mountPath: "/config"
            name: "config"        
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 8080
        args:
        - --web
        - --kubernetes
        - --configfile=/config/traefik.toml
        - --logLevel=INFO
        - --kubernetes.labelselector=expose in (external,internal)
        - --kubernetes.debugloggeneratedtemplate
        - --accesslog
        - --insecureskipverify
        # - --debug
---
