kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller-internal
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb-internal
    k8s-traefik: traefik  
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-serviceaccount
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-conf
      containers:
      - image: traefik
        name: traefik-ingress-lb
        volumeMounts:
          - mountPath: "/config"
            name: "config"        
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 8080
        args:
        - --web
        - --kubernetes
        - --configfile=/config/traefik.toml
        - --logLevel=INFO
        - --kubernetes.labelselector=expose=internal        
        # https://github.com/kubernetes/ingress-nginx/blob/master/README.md#running-multiple-ingress-controllers
        # https://docs.traefik.io/user-guide/kubernetes/
---
