apiVersion: v1
kind: PersistentVolume
metadata:
  name: realtime.certificateserver
  namespace: fabricrealtime
  labels:
    type: local
    namespace: fabricrealtime
spec:
  #persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/fabricrealtime"
  claimRef:
    namespace: fabricrealtime
    name: realtime.certificateserver
