kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nlp.mysqlserver
  namespace: fabricnlp  
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
