kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: realtime.certificateserver
  namespace: fabricrealtime  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi