kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: az-files-rabbitmqcert
  namespace: fabricrealtime  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
