kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
    k8s-traefik: traefik  
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      # run on master node so we use the IP of the master
      # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
      nodeSelector:
        dedicated: master
      # https://stackoverflow.com/questions/41999756/how-to-force-pods-deployments-to-master-nodes
      # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule              
      serviceAccountName: traefik-ingress-serviceaccount
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-conf
      containers:
      - image: traefik
        name: traefik-ingress-lb
        volumeMounts:
          - mountPath: "/config"
            name: "config"        
        ports:
          - containerPort: 80
          # set hostPort so the ingress shows up on the master node's IP
            hostPort: 80
          - containerPort: 443
            hostPort: 443
        args:
        - --web
        - --kubernetes
        - --configfile=/config/traefik.toml
        - --logLevel=INFO
---
