apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nlp-ingress
    namespace: fabricnlp
    labels:  
        expose: external    
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /solr
        backend:
          serviceName: solrserverpublic
          servicePort: 80
      - path: /nlpweb
        backend:
          serviceName: nlpserverpublic
          servicePort: 80          
      - path: /nlp
        backend:
          serviceName: nlpjobsserverpublic
          servicePort: 80          
