kind: Deployment
apiVersion: extensions/v1beta1
metadata:
# name for this pod
  name: interfaceengine
# namespace for this pod
  namespace: fabricrealtime  
  labels:
    app: interfaceengine
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate        
  selector:
    matchLabels:
      app: interfaceengine
  template:
    metadata:
      labels:
        app: interfaceengine
    spec:
      containers:
        # name of this pod
        - name: interfaceengine
          # image to pull
          image: healthcatalyst/fabric.docker.interfaceengine:latest
          # specify to always pull a new image
          imagePullPolicy: Always
          # environment variables
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
            - name: MYSQL_DATABASE
              value: mirthdb
            - name: MYSQL_USER
              value: mirthuser
            - name: HTTP_PORT
              value: "80"
            - name: HTTPS_PORT
              value: "443"
            - name: HTTP_CONTEXTPATH
              value: "/mirth/"
          ports:
            # expose port 3000
            - containerPort: 80
              # name of the port
              name: http
            - containerPort: 443
              # name of the port
              name: https 
            - containerPort: 6661
              # name of the port
              name: channel 
